### ISSUE TITLE
mt940 file upload leads to error page

### ISSUE THREAD

**Issue by Anis108** [sprankhub/bank-integration#10] opened 2015-12-21 20:36 UTC
The upload of an mt940 file leads to error page:

There has been an error processing your request

var/log/kinento.log:
2015-12-21T20:16:03+00:00 DEBUG (7): [kinento-bankintegration] Importing for bank 1

var/report/report includes following text:

a:5:{i:0;s:21:"Disallowed file type.";i:1;s:1248:"#0 /home/****_900/public_html/**_**/lib/Varien/File/Uploader.php(180): Varien_File_Uploader->_validateFile()
#1 /home/****_900/public_html/**_**/app/code/community/Kinento/Bankintegration/controllers/UploadController.php(77): Varien_File_Uploader->save('/home/*****900/...')
#2 /home/****_900/public_html/**_**/app/code/community/Kinento/Bankintegration/controllers/UploadController.php(36): Kinento_Bankintegration_UploadController->performImport(1)
#3 /home/****_900/public_html/**_**/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Kinento_Bankintegration_UploadController->import1Action()
#4 /home/****_900/public_html/**_**/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('import1')
#5 /home/****_900/public_html/**_**/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /home/****_900/public_html/**_**/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /home/****_900/public_html/**_**/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 /home/****_900/public_html/**_**/index.php(83): Mage::run('', 'store')
#9 {main}";s:3:"url";s:79:"/index.php/bankintegration/upload/import1/key/31c2f786f1a61bcb0a3c0a4d6f9244d0/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by sprankhub** [comment] 2016-01-04 11:59
I just committed a fix based on your example file: https://github.com/sprankhub/bank-integration/commit/ec8a388922df468ff2624bb6a0d688f91395f2d0
Please get the current version [here](https://github.com/sprankhub/bank-integration/archive/master.zip) and check if it solves your issue.

Hope that it works fine with it. Unfortunately, I cannot provide any extended support on this "old" version of the extension. Support for the paid version will follow ;)

**Comment by sprankhub** [comment] 2016-01-19 17:07
I close this due to inactivity. Please reopen if the issue is still present.

**Closed as completed by sprankhub** 2016-01-19 17:07 UTC
